import { createGroupEntities } from "./GroupEntityConverter";

test("convert groups", async () => {
  const groups = [
    {
      id: "89fac263-2430-48fd-9278-dacfdfc89792",
      deletedDateTime: undefined,
      classification: undefined,
      createdDateTime: "2019-04-23T18:06:05Z",
      creationOptions: [],
      description: "descr",
      displayName: "test group",
      groupTypes: [],
      mail: undefined,
      mailEnabled: false,
      mailNickname: "8bb2d1c34",
      onPremisesLastSyncDateTime: undefined,
      onPremisesSecurityIdentifier: undefined,
      onPremisesSyncEnabled: undefined,
      preferredDataLocation: undefined,
      proxyAddresses: [],
      renewedDateTime: "2019-04-23T18:06:05Z",
      resourceBehaviorOptions: [],
      resourceProvisioningOptions: [],
      securityEnabled: true,
      visibility: undefined,
      onPremisesProvisioningErrors: [],
    },
    {
      id: "89fac263-2430-48fd-9278-dacfdfc11111",
      deletedDateTime: undefined,
      classification: undefined,
      createdDateTime: "2019-04-23T18:06:05Z",
      creationOptions: [],
      description: "descr",
      displayName: undefined,
      groupTypes: [],
      mail: undefined,
      mailEnabled: false,
      mailNickname: "8bb2d1c34",
      onPremisesLastSyncDateTime: undefined,
      onPremisesSecurityIdentifier: undefined,
      onPremisesSyncEnabled: undefined,
      preferredDataLocation: undefined,
      proxyAddresses: [],
      renewedDateTime: "2019-04-23T18:06:05Z",
      resourceBehaviorOptions: [],
      resourceProvisioningOptions: [],
      securityEnabled: true,
      visibility: undefined,
      onPremisesProvisioningErrors: [],
    },
  ];

  const entities = createGroupEntities(groups);

  expect(entities).toEqual([
    {
      _class: "UserGroup",
      _key: "azure_user_group_89fac263-2430-48fd-9278-dacfdfc89792",
      _type: "azure_user_group",
      classification: undefined,
      createdDateTime: "2019-04-23T18:06:05Z",
      deletedDateTime: undefined,
      description: "descr",
      displayName: "test group",
      id: "89fac263-2430-48fd-9278-dacfdfc89792",
      mail: undefined,
      mailEnabled: false,
      mailNickname: "8bb2d1c34",
      renewedDateTime: "2019-04-23T18:06:05Z",
      securityEnabled: true,
    },
    {
      _class: "UserGroup",
      _key: "azure_user_group_89fac263-2430-48fd-9278-dacfdfc11111",
      _type: "azure_user_group",
      classification: undefined,
      createdDateTime: "2019-04-23T18:06:05Z",
      deletedDateTime: undefined,
      description: "descr",
      displayName: "",
      id: "89fac263-2430-48fd-9278-dacfdfc11111",
      mail: undefined,
      mailEnabled: false,
      mailNickname: "8bb2d1c34",
      renewedDateTime: "2019-04-23T18:06:05Z",
      securityEnabled: true,
    },
  ]);
});
