import { createUserEntities } from "./UserEntityConverter";

test("convert users", async () => {
  const users = [
    {
      businessPhones: ["+1 2223334444"],
      displayName: "bob white",
      givenName: "bob",
      jobTitle: "test title",
      mail: undefined,
      mobilePhone: "+1 2223334444",
      officeLocation: "DBP",
      preferredLanguage: undefined,
      surname: "white",
      userPrincipalName:
        "admin_test.example.com#EXT#@admintestexample.onmicrosoft.com",
      id: "abf00eda-02d6-4053-a077-eef036e1a4c8",
    },
    {
      businessPhones: [],
      displayName: "Second Test User",
      givenName: "Second",
      jobTitle: "Developer",
      mail: undefined,
      mobilePhone: undefined,
      officeLocation: undefined,
      preferredLanguage: undefined,
      surname: "Test",
      userPrincipalName: "second@admintestexample.onmicrosoft.com",
      id: "324e8daa-9c29-42a4-a74b-b9893e6d9750",
    },
    {
      businessPhones: [],
      displayName: undefined,
      givenName: undefined,
      jobTitle: undefined,
      mail: undefined,
      mobilePhone: undefined,
      officeLocation: undefined,
      preferredLanguage: undefined,
      surname: undefined,
      userPrincipalName: undefined,
      id: "19f7fe21-48c7-4cdb-ab87-99670e9f3af0",
    },
  ];
  const managers = [
    {
      user: {
        id: "abf00eda-02d6-4053-a077-eef036e1a4c8",
      },
      manager: {
        businessPhones: ["+1 2223334444"],
        displayName: "bob white",
        givenName: "bob",
        jobTitle: "test title",
        mail: undefined,
        mobilePhone: "+1 2223334444",
        officeLocation: "DBP",
        preferredLanguage: undefined,
        surname: "white",
        userPrincipalName:
          "admin_test.example.com#EXT#@admintestexample.onmicrosoft.com",
        id: "abf00eda-02d6-4053-a077-eef036e1a4c8",
      },
    },
  ];

  const entities = createUserEntities(users, managers);

  expect(entities).toEqual([
    {
      _class: "User",
      _key: "azure_user_abf00eda-02d6-4053-a077-eef036e1a4c8",
      _type: "azure_user",
      displayName: "bob white",
      email: "admin_test.example.com#EXT#@admintestexample.onmicrosoft.com",
      employeeNumber: undefined,
      employeeType: undefined,
      firstName: "bob",
      givenName: "bob",
      id: "abf00eda-02d6-4053-a077-eef036e1a4c8",
      jobTitle: "test title",
      lastName: "white",
      mail: undefined,
      manager: "bob white",
      managerEmail: undefined,
      managerId: undefined,
      mobilePhone: "+1 2223334444",
      name: "bob white",
      officeLocation: "DBP",
      preferredLanguage: undefined,
      surname: "white",
      title: "test title",
      userPrincipalName:
        "admin_test.example.com#EXT#@admintestexample.onmicrosoft.com",
      username: undefined,
    },
    {
      _class: "User",
      _key: "azure_user_324e8daa-9c29-42a4-a74b-b9893e6d9750",
      _type: "azure_user",
      displayName: "Second Test User",
      email: "second@admintestexample.onmicrosoft.com",
      employeeNumber: undefined,
      employeeType: undefined,
      firstName: "Second",
      givenName: "Second",
      id: "324e8daa-9c29-42a4-a74b-b9893e6d9750",
      jobTitle: "Developer",
      lastName: "Test",
      mail: undefined,
      mobilePhone: undefined,
      name: "Second Test User",
      officeLocation: undefined,
      preferredLanguage: undefined,
      surname: "Test",
      title: "Developer",
      userPrincipalName: "second@admintestexample.onmicrosoft.com",
      username: undefined,
    },
    {
      _class: "User",
      _key: "azure_user_19f7fe21-48c7-4cdb-ab87-99670e9f3af0",
      _type: "azure_user",
      displayName: undefined,
      email: undefined,
      employeeNumber: undefined,
      employeeType: undefined,
      firstName: undefined,
      givenName: undefined,
      id: "19f7fe21-48c7-4cdb-ab87-99670e9f3af0",
      jobTitle: undefined,
      lastName: undefined,
      mail: undefined,
      mobilePhone: undefined,
      name: undefined,
      officeLocation: undefined,
      preferredLanguage: undefined,
      surname: undefined,
      title: undefined,
      userPrincipalName: undefined,
      username: undefined,
    },
  ]);
});
