openapi: 3.0.1
info:
  title: '@jupiterone/graph-azure'
  description: A graph conversion tool for https://azure.microsoft.com/.
  x-cortex-git:
    github:
      repository: JupiterOne/graph-azure
  x-cortex-owners:
    - type: group
      name: JupiterOne/security
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-azure'
